### ISSUE TITLE
Could not find ZLIB

### ISSUE THREAD

**Issue by irish-bug** [zeek/zeek-docker#3]
Hey Justin,

I was trying to spin this up in CoreOS using Dockerfile 2.5 and got the following abort message:

-- Found BIND: /usr/lib/x86_64-linux-gnu/libresolv.so
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Error at aux/binpac/CMakeLists.txt:17 (message):
   Could not find prerequisite package 'ZLIB'

CMake Error at aux/binpac/CMakeLists.txt:19 (message):
  Configuration aborted due to missing prerequisites

CoreOS info:
Stable
1353.7.0
The Stable channel should be used by production clusters. Versions of CoreOS Container Linux are battle-tested within the Beta and Alpha channels before being promoted.

kernel:    4.9.24
rkt:         1.25.0
docker:  1.12.6

**Comment by JustinAzoff** [comment]
ah, looks like the apt-get line should install zlib1g-dev.  I updated the dockerfile in 6037a714a92a26952f3264598b9dbd17e6db0180 and that should fix it.  I'm rebuilding it now myself to verify that it works.

FYI, you can always just docker run broplatform/bro:2.5 (or any other version) which is where the image gets pushed to.

**Comment by JustinAzoff** [comment]
This is working now afaik.
