### ISSUE TITLE
Fails to listen on INADDR_ANY:47760

### ISSUE THREAD

**Issue by Nusto** [zeek/zeek-docker#8]
I am working on a centos 7 minimal install running docker 18.09.3
`Docker version 18.09.3, build 774a1f4`
when running `/bro/bin/broctl deploy` bro crashes, the results of running `diag` are below
My understanding of this error is that it is failing to bind

Dockerfile:
```
FROM broplatform/bro:2.6

RUN apt-get update
RUN apt-get install -y python vim gdb

EXPOSE 47760
```

docker ps:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
178769fc6e36        bro                 "/bin/sh -c '/bin/ba…"   38 minutes ago      Up 38 minutes       47760/tcp           bro

```

diag results:
> [BroControl] > diag
> [bro]
> 
> No core file found.
> 
> Bro 2.6
> Linux 3.10.0-957.5.1.el7.x86_64
> 
> Bro plugins: (none found)
> 
> ==== reporter.log
> #separator \x09
> #set_separator ,
> #empty_field (empty)
> #unset_field -
> #path reporter
> #open 2019-03-13-19-44-40
> #fields ts level message location
> #types time enum string string
> 0.000000 Reporter::ERROR Failed to listen on INADDR_ANY:47760 (Broker::listen(Broker::default_listen_address, Broker::default_port, Broker::default_listen_retry)) /usr/local/bro-2.6/spool/installed-scripts-do-not-touch/auto/standalone-layout.bro, line 6
> 0.000000 Reporter::ERROR Failed to listen on INADDR_ANY:47760 (Broker::listen(Broker::a, Broker::p, Broker::retry)) /usr/local/bro-2.6/share/bro/base/frameworks/broker/./main.bro, line 358
> 
> ==== stderr.log
> listening on eth0
> 
> 
> ==== stdout.log
> max memory size         (kbytes, -m) unlimited
> data seg size           (kbytes, -d) unlimited
> virtual memory          (kbytes, -v) unlimited
> core file size          (blocks, -c) unlimited
> 
> ==== .cmdline
> -i eth0 -U .status -p broctl -p broctl-live -p standalone -p local -p bro local.bro broctl broctl/standalone broctl/auto
> 
> ==== .env_vars
> PATH=/usr/local/bro-2.6/bin:/usr/local/bro-2.6/share/broctl/scripts:/bro/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> BROPATH=/usr/local/bro-2.6/spool/installed-scripts-do-not-touch/site::/usr/local/bro-2.6/spool/installed-scripts-do-not-touch/auto:/usr/local/bro-2.6/share/bro:/usr/local/bro-2.6/share/bro/policy:/usr/local/bro-2.6/share/bro/site
> CLUSTER_NODE=
> 
> ==== .status
> RUNNING [net_run]
> 
> ==== No prof.log
> 
> ==== packet_filter.log
> #separator \x09
> #set_separator ,
> #empty_field (empty)
> #unset_field -
> #path packet_filter
> #open 2019-03-13-19-44-40
> #fields ts node filter init  success
> #types time string string bool  bool
> 1552506280.164124  bro ip or not ip T T

**Comment by JustinAzoff** [comment]
Does it work if you add this in your dockerfile:

    env BRO_DEFAULT_LISTEN_ADDRESS 127.0.0.1

**Comment by Nusto** [comment]
I get a similar error

> ==== reporter.log
> #separator \x09
> #set_separator  ,
> #empty_field    (empty)
> #unset_field    -
> #path   reporter
> #open   2019-03-14-13-50-30
> #fields ts      level   message location
> #types  time    enum    string  string
> 0.000000        Reporter::ERROR Failed to listen on 127.0.0.1:47760 (Broker::listen(Broker::default_listen_address, Broker::default_port, Broker::default_listen_retry))  /usr/local/bro-2.6/spool/installed-scripts-do-not-touch/auto/standalone-layout.bro, line 6
> 0.000000        Reporter::ERROR Failed to listen on 127.0.0.1:47760 (Broker::listen(Broker::a, Broker::p, Broker::retry)) /usr/local/bro-2.6/share/bro/base/frameworks/broker/./main.bro, line 358

**Comment by JustinAzoff** [comment]
Very strange.. I'm not sure why this was presenting itself as an issue with broker, but broctl uses ps, and I had installed procps to fix the status command, and that actually fixed the problem:

```
FROM broplatform/bro:2.6

RUN apt-get update
RUN apt-get install -y python vim gdb procps

EXPOSE 47760
```

```
justin@mbp:~$ docker run -t -i --rm broctl_docker
root@e999f3e6defe:/# broctl deploy
checking configurations ...
installing ...
creating policy directories ...
installing site policies ...
generating standalone-layout.bro ...
generating local-networks.bro ...
generating broctl-config.bro ...
generating broctl-config.sh ...
stopping ...
stopping bro ...
starting ...
starting bro ...
root@e999f3e6defe:/# broctl status
Name         Type       Host          Status    Pid    Started
bro          standalone localhost     running   52     14 Mar 15:32:04
root@e999f3e6defe:/# ss -lp|grep bro
p_raw  UNCONN     0      0       *:eth0                   *                      users:(("bro",pid=52,fd=11))
tcp    LISTEN     0      0      :::47760                :::*                     users:(("bro",pid=52,fd=18))
tcp    LISTEN     0      0      :::47760                :::*                     users:(("bro",pid=52,fd=18))
```

**Comment by Nusto** [comment]
Thanks, It is working now!

**Comment by 0xxon** [comment]
Closing this, since this probably is no longer an issue.
